name: Update gh-pages

on:
  push:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - run: cd demo && npm i --force

      - name: Generate demo
        run: cd demo && npm run build

      - name: Deploy it to GH pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./demo/dist
